### ISSUE TITLE
roUrlTransfer.SetHeaders: Enumeration contains non-object

### ISSUE THREAD

**Issue by juan-manuel-p** [julio-alves/roku-libs#2]
https://github.com/juliomalves/roku-libs/blob/796d0aeacea371dfc119b8196e8026c80f3b334c/source/libs/http-request.brs#L17C16-L17C16

Small issue, it should be replaced by invalid.

**Comment by juliomalves** [comment]
Thanks for submitting this issue.

Addressed in https://github.com/juliomalves/roku-libs/commit/79204e486796c9be327a73daa2e6a0f51d53fb08.
